### ISSUE TITLE
Q: Why are the capi-flash tools delivered in binary?

### ISSUE THREAD

**Issue by fhaverkamp** [ibm-capi/capi-utils#1]
In general I assume that the tools do what is done here for the Nallatech card:
https://github.com/open-power/capiflash/blob/master/src/build/install/resources/capi_flash.pl
So is there any particular reason, why this is currently in binary?

**Comment by KennethWilke** [comment]
:+1: it's unusual for github to be a distribution platform for binaries. Since this project is MIT licensed it'd be good if the source was distributed in this repo and the pre-built binaries packaged as releases

**Comment by kenhill** [comment]
The tool is similar to the one used by capiflash. The main differences between the board/PSL releases are the location of the flash controller and the flash starting address for the `user` and `factory` partitions. Some of the information (addresses, offset, etc.) contained in the source code are not publicly available, so it was decided to post the binaries to avoid invalid binaries being created/circulated. I will review this decision internally with others on the team

**Comment by fhaverkamp** [comment]
Well, security by obfuscation is not really secure, don't you think? Would be nice if you could revert your decision in the spirit of openess. Thanks.

**Comment by kenhill** [comment]
An upcoming release will include the source code for the flash binaries
