### ISSUE TITLE
bad file extension error message is missleading

### ISSUE THREAD

**Issue by acastellane** [ibm-capi/capi-utils#17]
I suggest we change to
_# check file type
FILE_EXT=${1##*.}
if [[ ${fpga_type[$c]} == "Altera" ]]; then
  if [[ $FILE_EXT != "rbf" ]]; then
    printf "${bold}ERROR: ${normal} **Incorrect Altera file extension ! .rbf should be used.**\n"
    exit 0
  fi
else
  if [[ $FILE_EXT != "bin" ]]; then
    printf "${bold}ERROR: ${normal} **Incorrect file extension ! .bin file should used**.\n"
    exit 0
  fi
fi_

with regards, Alexandre

**Comment by jsvogt** [comment]
:+1: The message `Incorrect board type` had confused me as well when I tried one of our CI-tested .bin files that were converted to somename.bin.**good**.
@acastellane are you going to propose this change in a pull request?

**Comment by kenhill** [comment]
Fix merged into master
