### ISSUE TITLE
Q: Are there plans to publish this into System p Linux distros?

### ISSUE THREAD

**Issue by fhaverkamp** [ibm-capi/capi-utils#2]
Well and for this I wonder about an answer to this issue: https://github.com/ibm-capi/capi-utils/issues/1.

But in general, it is good to have now one central point where this functionality is hosted! Thanks.

**Comment by kenhill** [comment]
The tool is currently tested in Ubuntu with ppc64le support. A future goal would be to include this utility in the different linux distribution repositories. I will review https://github.com/ibm-capi/capi-utils/issues/1 with the team. In the near term, it may be easier to have a separate branch for big endian support

**Comment by fhaverkamp** [comment]
Did you try on RHEL7.3? I think that is the other ppc64le Linux distribution out there.

**Comment by kenhill** [comment]
We currently suggest using either Ubuntu 16.04 or RHEL 7.3. The existing package should work on both platforms. 

Please note, CAPI is not supported with big endian as suggested earlier
