### ISSUE TITLE
Add a timeout to the reset to the factory image!

### ISSUE THREAD

**Issue by bmesnet** [ibm-capi/capi-utils#24]
The new capi-utils starts with a reset to the factory image. If the factory image is not "good" enough, then the reset procedure never ends and a reboot of the server is needed !
A timeout and an information message could be welcome !

**Comment by jsvogt** [comment]
:+1: The server reboot is still needed in that case, even after the timeout. At least the message would inform the user that a reboot may be required.

**Comment by bmesnet** [comment]
_Adding a comment:_ 
I always worked until today downloading an image in the user area, doing resets without testing the factory image nor rebooting the server.
Why should we now consider that this new capi-utils release doesn't allow anymore a user to work on his user image even if he has a not "good" enough factory image?

**Comment by kenhill** [comment]
@bmesnet, the master branch has a default timeout of 30 seconds. The CAPI adapter should always be able to perst back to the factory image. This is related to the perst issue that has come up in the lab. It is not the case that there is a bad factory image on the card, but the perst is not starting/completing successfully. There is a logic fix being pushed into the DCP files soon to address the perst issues.

**Comment by bmesnet** [comment]
All cards now have always this factory image and a user image.
To display  which image is actually loaded, type `snap_find_card -v -A ALL `and it will display all information about which image is loaded and which image will be loaded at next reboot
