### ISSUE TITLE
additionnal test and warning when card is not the expected one

### ISSUE THREAD

**Issue by acastellane** [ibm-capi/capi-utils#26]
Hi,
when trying to program an ADKU3 card for a SNAP application, I loaded a N250S bin file by error.
As it had the proper extension, there was not warning.
The card was then recognized by SNAP tools as a N250S, although it was a ADKU3.
Fortunately it seems I didn't break any I/Os ! So any test / warning would be welcomed of possible.
Thanks

**Comment by kenhill** [comment]
Unfortunately *.bin is a raw binary and does not contain information that would identify the target board. We can revisit using either a *.bit file and stripping the header off or introducing our own file format.

**Comment by bmesnet** [comment]
Solution proposed in issue #47
