### ISSUE TITLE
Q: Which license is it?

### ISSUE THREAD

**Issue by fhaverkamp** [ibm-capi/capi-utils#3]
MIT like in LICENCE or Apache2 like in NOTICES? Or both?

**Comment by kenhill** [comment]
Apache2. The project was cloned from an MIT licensed project. I will post an update soon to remove the uncertainty

**Comment by fhaverkamp** [comment]
It still shows MIT as license.

**Comment by kenhill** [comment]
The LICENSE file has been updated to clarify the license terms for the project

**Comment by fhaverkamp** [comment]
Thanks.
