### ISSUE TITLE
Error handling: Trying to call /usr/local/bin/capi-flash-

### ISSUE THREAD

**Issue by fhaverkamp** [ibm-capi/capi-utils#5]
Hi,

We broke our card and tried to recover with this command:

haver@tul2eth3:~$ sudo capi-flash-script.sh fw_OPENCL128DDR3_1116-000_ku3.bin 

Current date:
Wed Nov  9 15:00:56 CET 2016

#       Card                           Flashed                       by                   Image
pcilib: Cannot open /sys/bus/pci/devices/0044:01:00.0/config
lspci: Unable to read the standard configuration space header of device 0044:01:00.0

Which card do you want to flash? [0-0] 0

Do you want to continue to flash fw_OPENCL128DDR3_1116-000_ku3.bin to card0? [y/n] y

/usr/local/bin/capi-flash-script.sh: line 144: /usr/local/bin/capi-flash-: No such file or directory
ERROR: Something went wrong
Preparing to reset card
Resetting card
/usr/local/bin/capi-flash-script.sh: line 150: /sys/class/cxl/card0/load_image_on_perst: Permission denied
haver@tul2eth3:~$ ll /usr/local/bin/
total 16924
drwxr-xr-x  4 root root     4096 Nov  9 11:27 ./
drwxr-xr-x 11 root root     4096 Jul 25 09:25 ../
-rwxr-xr-x  1 root root    18768 Sep 11  2015 capi-flash-0000*
-rwxr-xr-x  1 root root    72032 Sep 11  2015 capi-flash-2001*
-rwxr-xr-x  1 root root    72032 Nov  9 11:27 capi-flash-AlphaData7v3*
-rwxr-xr-x  1 root root    72032 Nov  9 11:27 capi-flash-AlphaDataKU115*
-rwxr-xr-x  1 root root    72032 Nov  9 11:27 capi-flash-AlphaDataKU60*
-rwxr-xr-x  1 root root    18768 Nov  9 11:27 capi-flash-Nallatech*
-rwxr-xr-x  1 root root     4565 Nov  9 11:27 capi-flash-script.sh*
-rwxr-xr-x  1 root root    16187 Sep 10  2015 capi_flash*

Event though this was not clean anyways, I suggest that the capi-flash-script.sh stops me from doing strange stuff as early as possible. It ended up trying to all a /usr/local/bin/capi-flash- binary, which of course did not exist.

Maybe there is a way to avoid this in the first place?

Thanks

Frank

**Comment by kenhill** [comment]
Added a check to verify a CAPI device exists before trying to flash the board
