### ISSUE TITLE
core dump when trying to update our KU3 card

### ISSUE THREAD

**Issue by fhaverkamp** [ibm-capi/capi-utils#6]
root@tul2eth3:~# capi-flash-script.sh /tmp/fw_ddr3_reiner.bin 

Current date:
Wed Nov  9 14:55:29 CET 2016

#       Card                           Flashed                       by                   Image
card0    AlphaDataKU60 Xilinx          Wed Nov  9 11:28:20 CET 2016  haver                fw_OPENCL128DDR3_1116-000_ku3.bin

Which card do you want to flash? [0-0] 0

Do you want to continue to flash /tmp/fw_ddr3_reiner.bin to card0? [y/n] y

Device ID: 0477
Vendor ID: 1014
  VSEC Length/VSEC Rev/VSEC ID: 0x08001280
    Version 0.12

Programming User Partition with /tmp/fw_ddr3_reiner.bin
  Program ->  for Size: 44 in blocks (32K Words or 128K Bytes)

Erasing Flash
......

Programming Flash
Writing Buffer: 11519        

Port not ready 6634729 times

Verifying Flash
Reading Block: 44        

Erase Time:   38 seconds
Program Time: 25 seconds
Verify Time:  7 seconds
Total Time:   70 seconds

Preparing to reset card
Resetting card
Segmentation fault

We try to collect the core dump if possible. I fear it is not available. I added:
    https://github.com/fhaverkamp/capi-utils/commit/5ee1bbc8fb05e4b9eec1e8f5eec57df058d8830d to propose ulimits -c unlimited, such that we get one in future. What do you think?

**Comment by fhaverkamp** [comment]
It appears as if the flashing was successful after all. But leaving a core dump and a disappearing card is not so nice. We had to do a power off and power on to get the card back. So dynamic reactivation of the capi card after update seems not trouble free.

**Comment by kenhill** [comment]
I accepted the addition for `ulimits -c unlimited`. Did the card disappear after several flashing attempts? By default the EEH handler will quarantine a PCI card after ~5 resets within a hour. A message should be logged to the kernel log if this is the case and can be seen using `dmesg` command. The limit can be raised using this: `echo 10000 | sudo tee /sys/kernel/debug/powerpc/eeh_max_freezes`

I do not know what would cause the segmentation fault. Is this an often occurrence with the KU60? If so, can you post the O/S and kernel you are using

**Comment by fhaverkamp** [comment]
haver@tul2eth3:~$ uname -a
Linux tul2eth3 4.4.0-43-generic #63-Ubuntu SMP Wed Oct 12 13:45:41 UTC 2016 ppc64le ppc64le ppc64le GNU/Linux
haver@tul2eth3:~$ 

We just flashed two times. What about setting the eeh_max_freeze yourself to something high. You could put it back after flashing went well. I hope that the ulimits -c helps to gather a core dump for you, just in case it happens again. Since the bitstream seemed to get flashed OK, it appears that reloading it caused the problem.

haver@tul2eth3:~$ cat /sys/class/cxl/card0/psl_revision 
12291

Does that help you to figure out the exact version of the card? Our folks call it Alpha-Data KU3 and not KU60.

Or this:
haver@tul2eth3:~$ sudo lspci -vvs 0044:01:00.0
0044:01:00.0 Processing accelerators: IBM Device 0477 (rev 01) (prog-if ff)
	Control: I/O- Mem+ BusMaster- SpecCycle- MemWINV- VGASnoop- ParErr+ Stepping- SERR+ FastB2B- DisINTx-
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Interrupt: pin A routed to IRQ 225
	Region 0: Memory at 3d4000000000 (64-bit, prefetchable) [size=256M]
	Region 2: Memory at 3d4010000000 (64-bit, prefetchable) [size=128K]
	Region 4: Memory at <ignored> (64-bit, prefetchable) [size=256G]
	Capabilities: [80] Power Management version 3
		Flags: PMEClk- DSI- D1- D2- AuxCurrent=0mA PME(D0-,D1-,D2-,D3hot-,D3cold-)
		Status: D0 NoSoftRst+ PME-Enable- DSel=0 DScale=0 PME-
	Capabilities: [90] MSI: Enable- Count=1/4 Maskable- 64bit+
		Address: 0000000000000000  Data: 0000
	Capabilities: [c0] Express (v2) Endpoint, MSI 00
		DevCap:	MaxPayload 128 bytes, PhantFunc 0, Latency L0s <64ns, L1 <1us
			ExtTag- AttnBtn- AttnInd- PwrInd- RBE+ FLReset-
		DevCtl:	Report errors: Correctable- Non-Fatal+ Fatal+ Unsupported+
			RlxdOrd+ ExtTag- PhantFunc- AuxPwr- NoSnoop+
			MaxPayload 128 bytes, MaxReadReq 512 bytes
		DevSta:	CorrErr- UncorrErr- FatalErr+ UnsuppReq- AuxPwr- TransPend-
		LnkCap:	Port #0, Speed 8GT/s, Width x8, ASPM not supported, Exit Latency L0s unlimited, L1 unlimited
			ClockPM- Surprise- LLActRep- BwNot- ASPMOptComp+
		LnkCtl:	ASPM Disabled; RCB 64 bytes Disabled- CommClk+
			ExtSynch- ClockPM- AutWidDis- BWInt- AutBWInt-
		LnkSta:	Speed 8GT/s, Width x8, TrErr- Train- SlotClk+ DLActive- BWMgmt- ABWMgmt-
		DevCap2: Completion Timeout: Range B, TimeoutDis+, LTR-, OBFF Not Supported
		DevCtl2: Completion Timeout: 50us to 50ms, TimeoutDis+, LTR-, OBFF Disabled
		LnkCtl2: Target Link Speed: 8GT/s, EnterCompliance- SpeedDis-
			 Transmit Margin: Normal Operating Range, EnterModifiedCompliance- ComplianceSOS-
			 Compliance De-emphasis: -6dB
		LnkSta2: Current De-emphasis Level: -3.5dB, EqualizationComplete+, EqualizationPhase1+
			 EqualizationPhase2+, EqualizationPhase3+, LinkEqualizationRequest-
	Capabilities: [100 v2] Advanced Error Reporting
		UESta:	DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
		UEMsk:	DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
		UESvrt:	DLP+ SDES+ TLP- FCP+ CmpltTO- CmpltAbrt- UnxCmplt- RxOF+ MalfTLP+ ECRC- UnsupReq- ACSViol-
		CESta:	RxErr- BadTLP- BadDLLP- Rollover- Timeout- NonFatalErr-
		CEMsk:	RxErr- BadTLP- BadDLLP- Rollover- Timeout- NonFatalErr+
		AERCap:	First Error Pointer: 00, GenCap- CGenEn- ChkCap- ChkEn-
	Capabilities: [300 v1] #19
	Capabilities: [400 v1] Vendor Specific Information: ID=1280 Rev=0 Len=080 <?>
	Kernel driver in use: cxl-pci
	Kernel modules: cxl

There seems to be no VPD as we have it for the Nallatech FPGA card.

**Comment by kenhill** [comment]
I will have to investigate this a bit more. I have not observed this behavior locally and believe you are the first to report problems with the KU3. 

Also, the KU3 and KU60 refer to the same CAPI adapter. Alpha-Data is using similar naming conventions for their boards to match the Xilinx FPGAs. In this case, KU3 is the model of the Alpha-Data board and KU60 refers to the Xilinx FPGA that is populated.

**Comment by fhaverkamp** [comment]
Hi Ken,

let us close this one. We have now setup the ulimits nicely, such that if it re-occurs, you get some debug data. Currently it is not really reproducible.

Frank
